### ISSUE TITLE
Successful payment is created twice

### ISSUE THREAD

**Issue by fuchsbart** [wirecard/prestashop-ee#237]
### Versions

**PrestaShop version:** 1.7.5.1 (fresh installation, no modifications)
**PHP version:** 7.1

### Issue

With successful orders the payment is created twice in Prestashop. Error occurs with Credit Card 3DS and Sofort Payment. For Sofort Payments one with transaction ID and once without, for Credit Card both Payments have a Transaction ID.

![Bildschirmfoto 2019-10-31 um 10 47 37](https://user-images.githubusercontent.com/30295473/67936583-546f6f00-fbcc-11e9-8d81-0fb87f64cf2a.png)
![Bildschirmfoto 2019-10-31 um 10 47 21](https://user-images.githubusercontent.com/30295473/67936585-55080580-fbcc-11e9-9835-87729b036fdf.png)

**Comment by tomazpu** [comment]
Hello @fuchsbart, 

I reproduced the issue with Sofort. And created an issue that will be fixed.

For the Credit Card can u please tell me if you did an purchase or an authorize?

Best regards, 
Tomaz

**Comment by fuchsbart** [comment]
Hello, it's configured as purchase.

**Comment by tomazpu** [comment]
Hi @fuchsbart,

today we released a new version 2.4.0, where your described issue should be fixed.

Best regards, 
Tomaz

**Comment by fuchsbart** [comment]
Dear @tomazpu, I just tested the new release. A successful credit card payment is still shown as two payments in the Prestashop Backend. One time without Transaction ID and with an amount of 0, one time with Transaction ID and the right amount.

![Bildschirmfoto 2019-11-15 um 14 49 33](https://user-images.githubusercontent.com/30295473/68948130-7f0a1c00-07b7-11ea-9cc3-9750dc8b126c.png)
![Bildschirmfoto 2019-11-15 um 14 49 17](https://user-images.githubusercontent.com/30295473/68948132-7f0a1c00-07b7-11ea-8b2b-7c14a7ef2edb.png)

**Comment by tomazpu** [comment]
Hi, 

that's correct and are expected behavior. As we do not change the shop default behavior(on an order creation a payment is created), also this makes it clear that the order was initiated on 14:48:15 and then finished and paid at 14:48:25. Also, you see that the invoice is created when the payment is really done. 

If you have any input on why this is not good in your use case please comment here and I will give input to the business analyst.

Best regards,
Tomaz

**Comment by fuchsbart** [comment]
I can understand that the payment procedure between Prestashop and Wirecard works like this. But if you compare the functions of well-known payment modules for Prestashop (like PayPal, Heidelpay or Stripe) with it, this way of listing the payment is unusual. As you say yourself, the payment over €0.00 only shows that it was initiated. It is a status that must surely appear in the WEP wirecard backend, but not in the shop system under "Payments" for the order. There is only one payment (as you note) that is "really done". Not only does it look wrong, it's a special thing that I have to explain and document to every employee who works with our shopbackend. You could solve it together with issue #235

**Comment by tomazpu** [comment]
Hi, 

thank you for your input. I understand your point of view. I will give the input to are business analyst.

Best regards,
Tomaz
